CREATE TABLE country (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  region varchar(100) DEFAULT NULL,
  three_letter_code varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY name (name)
);

INSERT INTO country VALUES
(1,'Argentina','South America','ARG'),
(2,'Australia','Oceania','AUT'),
(3,'Austria','Europe','AUS'),
(4,'Belgium','Europe','BEL'),
(5,'Bolivia','South America','BOL'),
(6,'Brazil','South America','BRA'),
(7,'Bulgaria','Europe','BUL'),
(8,'Canada','North America','CAN'),
(9,'Chile','South America','CHI'),
(10,'China','Asia','CHN'),
(11,'Colombia','South America','COL'),
(12,'Croatia','Europe','CRO'),
(13,'Cyprus','Europe','CYP'),
(14,'Czech Republic','Europe','CZC'),
(15,'Denmark','Europe','DEN'),
(16,'Ecuador','South America','ECU'),
(17,'Egypt','Africa','EGY'),
(18,'Finland','Europe','FIN'),
(19,'France','Europe','FRA'),
(20,'Germany','Europe','GER'),
(21,'Greece','Europe','GRE'),
(22,'Hungary','Europe','HUN'),
(23,'Iceland','Europe','ICE'),
(24,'Ireland','Europe','IRL'),
(25,'Israel','Asia','ISR'),
(26,'Italy','Europe','ITA'),
(27,'Jamaica','Asia','JAM'),
(28,'Japan','Asia','JPN'),
(29,'Korea, Republic of','Asia','KOR'),
(30,'Latvia','Europe','LAT'),
(31,'Lithuania','Europe','LIT'),
(32,'Mexico','Europe','MEX'),
(33,'Netherlands','Europe','NED'),
(34,'Norway','Europe','NOR'),
(35,'Paraguay','South America','PAR'),
(36,'Peru','South America','PER'),
(37,'Poland','Europe','POL'),
(38,'Portugal','South America','POR'),
(39,'Qatar','Asia','QAT'),
(40,'Romania','Europe','PER'),
(41,'Russian Federation','Europe','RUS'),
(42,'Saudi Arabia','Asia','SAU'),
(43,'Serbia','Europe','SER'),
(44,'Slovakia','Europe','SLK'),
(45,'Slovenia','Europe','SLN'),
(46,'South Africa','Africa','ZAF'),
(47,'Spain','Europe','ESP'),
(48,'Sweden','Europe','SWE'),
(49,'Switzerland','Europe','SWT'),
(50,'Tunisia','Europe','TUN'),
(51,'Turkey','Europe','TUR'),
(52,'Ukraine','Europe','UKR'),
(53,'United Arab Emirates','Europe','UAE'),
(54,'United Kingdom','Europe','GBR'),
(55,'United States','North America','USA'),
(56,'Uruguay','Europe','URU'),
(57,'Costa Rica','Central America','CRC');